### PR TITLE
Output Pulsar Version

### PR DESCRIPTION
**Pull request by confused-Techie**
Small PR to output the version of Pulsar that is used to test with.

Can be helpful when investigating bugs or behavior.

If accepted, the readme has already been updated with the next tag that would be used here.

### CODE REVIEW

**Comment by Meadowsys** [comment]
maybe make it print out something like "Pulsar version 1.103.0"? so its a little bit more obvious what it is?

**Comment by confused-Techie** [comment]
@Meadowsys this just uses the built in `pulsar -v` which should print something like:

```bash
Pulsar  : 1.103.0
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0
```

**Comment by Meadowsys** [comment]
ooh right! disregard then, heh ><

**Review by Spiker985 — COMMENTED** [review]
While technically you can already see what version it downloaded, this provides a more consistent output.

Maybe we add a comment stating why we had to add another step? "When exporting to the PATH the information is only available to subsequent steps - <link to documentation>"

Unrelated:
Probably should shim the Windows "apm" call, to be "ppm"

But that would also be fixed if we upstreamed that change to ppm itself.

**Comment by confused-Techie** [comment]
@Spiker985 I couldn't find the output in the previous test runs, but yeah since the additional step works I'll add a comment

**Comment by Spiker985** [comment]
There actually is some GitHub Actions documentation regarding that phenomenon if you want to use their verbiage and link

Otherwise, that message works for me

**Comment by Spiker985** [comment]
> @Spiker985 I couldn't find the output in the previous test runs, but yeah since the additional step works I'll add a comment

Ironically enough, the test for the action itself prints out the version to make sure pulsar is available _as_ `pulsar`

**Comment by confused-Techie** [comment]
@Spiker985 Aha yeah, it's printed a lot here, but not so much in CI using it.

But you were right GitHub's docs were much more concise than what I wrote, so I updated the comment there

**Comment by Spiker985** [comment]
Inside the test workflow, I had also added `pulsar --package list` so that you had a concise listing of the version and the packages and their versions

Do you think we should add that as well?

I think it adds a definiteness that would be extremely helpful for troubleshooting

The only reason I didn't include it to begin with, was because I reasoned if someone wanted that info they could add a step for it - but if it's for troubleshooting purposes, knowing what package versions Pulsar came with is invaluable

**Comment by Spiker985** [comment]
If we do, we can drop that step from the CI, since it would be included in the install

**Comment by confused-Techie** [comment]
@Spiker985 Yeah that's actually a good idea, so I can go ahead and add that as well, and I suppose for the test here do we want to change it just to list the version? Or remove it totally? I'm not totally sure how GitHub Actions will report the action though if it fails during the setup like that, but I'd assume it'll still log a failure.

**Comment by Spiker985** [comment]
We can just drop the "run" step in the test.yml CI. If it cannot execute the version commands, it'll fail the "install" step instead

**Review by Spiker985 — APPROVED** [review]

**Comment by confused-Techie** [comment]
Alright @Spiker985 with your approval here, and I've added your last request I'll go ahead and merge this one, I appreciate your review!

**Comment by Spiker985** [comment]
> Alright @Spiker985 with your approval here, and I've added your last request I'll go ahead and merge this one, I appreciate your review!

No problem, feel free to request review on other items as well, if you want

**Comment by confused-Techie** [comment]
@Spiker985 Might take you up on that offer actually, thank you 😊

**Pull request merged**
